sudo: false
language: python
matrix:
  include:
    # CPython 2.7
    - python: 2.7
      env: TOXENV=py27-travis-integ-slow
    # CPython 3.5
    - python: 3.5
      env: TOXENV=py35-travis-integ-slow
    # CPython 3.6
    - python: 3.6
      env: TOXENV=py36-travis-integ-slow
    # CPython 3.7
    # xenial + sudo are currently needed to get 3.7
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      env: TOXENV=py37-travis-integ-slow
      dist: xenial
      sudo: true
install:
    # Clean up because Travis doesn't
    # https://github.com/travis-ci/travis-ci/issues/7940
    - if [[ $TRAVIS_SUDO ]]; then sudo rm -f /etc/boto.cfg; fi
    - pip install tox
script: travis_wait 60 tox -- -vv
