version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: python3_7
      buildspec: codebuild/python3.7.yml
    - identifier: python3_8
      buildspec: codebuild/python3.8.yml
    - identifier: python3_9
      buildspec: codebuild/python3.9.yml
    - identifier: python3_10
      buildspec: codebuild/python3.10.yml

    - identifier: code_coverage
      buildspec: codebuild/coverage/coverage.yml
