version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: python3_7
      buildspec: codebuild/python3.7.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: python3_8
      buildspec: codebuild/python3.8.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: python3_9
      buildspec: codebuild/python3.9.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: python3_10
      buildspec: codebuild/python3.10.yml
      env:
        image: aws/codebuild/standard:6.0
    - identifier: python3_11
      buildspec: codebuild/python3.11.yml
      env:
        image: aws/codebuild/standard:7.0
    - identifier: python3_12
      buildspec: codebuild/python3.12.yml
      env:
        image: aws/codebuild/standard:7.0        
    - identifier: code_coverage
      buildspec: codebuild/coverage/coverage.yml
