# This workflow runs static analysis checks on pull requests.
name: static analysis

on:
  pull_request:
  push:
  # Run once a day
  schedule:
    - cron: '0 0 * * *'

jobs:
  analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        category:
# Disabled pending completion of integration
# https://github.com/aws/aws-dynamodb-encryption-python/issues/66
#          - mypy-py2
#          - mypy-py3
          - bandit
          - doc8
          - readme
          - docs
          - flake8
          - pylint
          - flake8-tests
          - flake8-examples
          - pylint-tests
          - pylint-examples
          - black-check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r dev_requirements/ci-requirements.txt
      - name: check
        env:
          TOXENV: ${{ matrix.category }}
        run: tox -- -vv
