name: Local Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          - 2.7
          - 3.4
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.x
        categories:
          - local-slow
        # x86 builds are only meaningful for Windows
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-latest
            architecture: x86
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.architecture }}
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox
      - name: run test
        env:
          TOXENV: ${{ matrix.category }}
        run: tox -- -vv
